services:
  db:
    image: postgres:14-alpine
    container_name: picotrake_db
    env_file:
      - .env.db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: picotrake_api
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env.api
volumes:
  postgres_data: